version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: avito-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: avito-app
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/yourdb
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
